# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/attica': '@stable'
    'frameworks/karchive': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/kcodecs': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kdeclarative': '@stable'
    'frameworks/kdnssd': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kglobalaccel': '@stable'
    'frameworks/kguiaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kirigami': '@stable'
    'frameworks/knewstuff': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/kpackage': '@stable'
    'frameworks/ktexteditor': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'frameworks/solid': '@stable'
    'frameworks/threadweaver': '@stable'
    'libraries/qca' : '@latest'
    'libraries/phonon': '@stable'
