/* config.h. Generated by cmake from config.h.cmake */

/* have HELIX */
/* #undef HAVE_HELIX */

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT ${SIZEOF_INT}

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG ${SIZEOF_LONG}

/* have LIBVISUAL */
#cmakedefine HAVE_LIBVISUAL 1

/* have mp4v2 */
/* #undef HAVE_MP4V2 */

/* Define to 1 if you have the <mp4.h> header file. */
/* #undef HAVE_MP4_H */

/* have NMM */
/* #undef HAVE_NMM */

/* have Qt with OpenGL support */
/* #undef HAVE_QGLWIDGET */

/* Define to 1 if you have the `statvfs' function. */
#define HAVE_STATVFS 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <systems.h> header file. */
/* #undef HAVE_SYSTEMS_H */

/* have TagLib */
#define HAVE_TAGLIB 1

/* have TunePimp */
/* #undef HAVE_TUNEPIMP */

/* support ALSA in the helix-engine */
/* #undef USE_HELIX_ALSA */

/* MySql database support enabled */
#cmakedefine USE_MYSQL 1

/* Postgresql database support enabled */
#cmakedefine USE_POSTGRESQL 1

/* Define the path to XMMS plugins */
#define XMMS_PLUGIN_PATH "/usr/lib/xmms/Visualization"
