/* config-amarok.h. Generated by cmake from config-amarok.h.cmake */

/* have TagLib */
#cmakedefine TAGLIB_FOUND 1

/* Whether TagLib::FileName is a struct supporting wide characters or just a typedef */
#cmakedefine COMPLEX_TAGLIB_FILENAME 1

/* have TagLib-Extras */
#cmakedefine TAGLIB_EXTRAS_FOUND 1

/* have module file format support in TagLib */
#cmakedefine TAGLIB_MOD_FOUND 1

/* have QtCrypto the Qt crypto architecture */
#cmakedefine QCA2_FOUND 1

/* have Qt bindings */
#cmakedefine QTSCRIPTQTBINDINGS_FOUND 1

/* If liblastfm is found */
#cmakedefine HAVE_LIBLASTFM 1

/* If libofa is found */
#cmakedefine HAVE_LIBOFA 1

/* Whether cmake build type is debug */
#cmakedefine DEBUG_BUILD_TYPE
