/* config.h. Generated by cmake from config.h.cmake */

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT ${SIZEOF_INT}

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG ${SIZEOF_LONG}

/* have LIBVISUAL */
#cmakedefine HAVE_LIBVISUAL 1

/* have mp4v2 */
/* #undef HAVE_MP4V2 */

/* Define to 1 if you have the <mp4.h> header file. */
/* #undef HAVE_MP4_H */

/* have Qt with OpenGL support */
/* #undef HAVE_QGLWIDGET */

/* Define to 1 if you have the `statvfs' function. */
#define HAVE_STATVFS 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <systems.h> header file. */
/* #undef HAVE_SYSTEMS_H */

/* have TagLib */
#define HAVE_TAGLIB 1

/* MySql database support enabled */
#cmakedefine USE_MYSQL 1

/* Whether taglib exposes filenames as TagLib::FileName type */
#cmakedefine HAVE_TAGLIB_FILENAME 1

/* Whether TagLib::FileName is a struct supporting wide characters or just a typedef */
#cmakedefine COMPLEX_TAGLIB_FILENAME 1

/* Define to 1 if you networkmanager is found */
#cmakedefine HAVE_NETWORKMANAGER 1
