/* config.h. Generated by cmake from config.h.cmake */

/* have HELIX */
/* #undef HAVE_HELIX */

/* have ifp */
#cmakedefine HAVE_IFP 1

/* Define to 1 if you have the `itdb_get_mountpoint' function. */
/* #undef HAVE_ITDB_GET_MOUNTPOINT */

/* have libgpod movie flag */
/* #undef HAVE_ITDB_MOVIE_FLAG */

/* Define to 1 if you have the `itdb_track_set_thumbnails' function. */
#define HAVE_ITDB_TRACK_SET_THUMBNAILS 1

/* have libgpod */
#define HAVE_LIBGPOD 1

/* Define if you have libjpeg */
#cmakedefine HAVE_LIBJPEG 1

/* have libnjb */
#cmakedefine HAVE_LIBNJB 1

/* Define if you have libpng */
#cmakedefine HAVE_LIBPNG 1

/* Define if you have a working libpthread (will enable threaded code) */
#define HAVE_LIBPTHREAD 1

/* have LIBVISUAL */
#cmakedefine HAVE_LIBVISUAL 1

/* Define if you have libz */
#define HAVE_LIBZ 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* have mp4v2 */
/* #undef HAVE_MP4V2 */

/* Define to 1 if you have the <mp4.h> header file. */
/* #undef HAVE_MP4_H */

/* have NMM */
/* #undef HAVE_NMM */

/* Define if your system needs _NSGetEnviron to set up the environment */
/* #undef HAVE_NSGETENVIRON */

/* have Qt with OpenGL support */
/* #undef HAVE_QGLWIDGET */

/* Define to 1 if you have the `statvfs' function. */
#define HAVE_STATVFS 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <systems.h> header file. */
/* #undef HAVE_SYSTEMS_H */

/* have TagLib */
#define HAVE_TAGLIB 1

/* have TunePimp */
/* #undef HAVE_TUNEPIMP */

/* support ALSA in the helix-engine */
/* #undef USE_HELIX_ALSA */

/* MySql database support enabled */
#cmakedefine USE_MYSQL 1

/* Postgresql database support enabled */
#cmakedefine USE_POSTGRESQL 1

/* Define the path to XMMS plugins */
#define XMMS_PLUGIN_PATH "/usr/lib/xmms/Visualization"
