/* config-amarok-test.h. Generated by cmake from config-amarok-test.h.cmake */

/* The root of the test data in Amarok's source tree. Use this if you have to access uninstalled test data */
#define AMAROK_TEST_DIR ${AMAROK_TEST_TREE}
