#!/bin/bash

source /opt/amarok-nightly/neon/data/varsrc

if [ -x /opt/amarok-nightly/bin/amarok ]; then
  /opt/amarok-nightly/bin/kbuildsycoca4
  /opt/amarok-nightly/bin/amarok --style oxygen "$@"
else
  echo "Please install the amarok-nightly package or build amarok from source."
fi
