#!/bin/bash

source /opt/amarok-nightly/neon/data/varsrc

if [ -x /opt/amarok-nightly/bin/kcmshell4 ]; then
  /opt/amarok-nightly/bin/kbuildsycoca4
  /opt/amarok-nightly/bin/kcmshell4 kcm_phonon
else
  echo "Please install the amarok-nightly-kdebase-runtime package or build kdebase-runtime from source."
fi
