#!/bin/bash

source /opt/amarok-nightly/neon/data/varsrc

export KDE_COLOR_DEBUG=1
export QTEST_COLORED=1

  cmake "../" -DCMAKE_INSTALL_PREFIX=$NEONDIR -DCMAKE_BUILD_TYPE=debugfull && \
  nice make -j2 && \
  sudo make install;
