/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -v -i strigitypes.h -p XesamDbus XesamInterface.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "XesamDbus.h"

/*
 * Implementation of interface class OrgFreedesktopDBusIntrospectableInterface
 */

OrgFreedesktopDBusIntrospectableInterface::OrgFreedesktopDBusIntrospectableInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopDBusIntrospectableInterface::~OrgFreedesktopDBusIntrospectableInterface()
{
}

/*
 * Implementation of interface class OrgFreedesktopXesamSearchInterface
 */

OrgFreedesktopXesamSearchInterface::OrgFreedesktopXesamSearchInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopXesamSearchInterface::~OrgFreedesktopXesamSearchInterface()
{
}

#include "XesamDbus.moc"
