#!/bin/sh

/usr/bin/amarok-nightly-vars

export KDE_COLOR_DEBUG=1
export QTEST_COLORED=1

  cmake "../" -DCMAKE_INSTALL_PREFIX=$NEONDIR -DCMAKE_BUILD_TYPE=debugfull && \
  nice make -j2 && \
  make install;

echo "WARNING!!!!!!!: the current shell is configured for Project Neon (Amarok Nightly Builds), you really _DO NOT_ want to start any GUI application besides amarok-nightly!!!"
