debian/tmp/usr/share/apps/amarok/*
debian/tmp/usr/share/doc/*
debian/tmp/usr/share/icons/*
debian/tmp/usr/share/locale/*

debian/tmp/usr/share/config.kcfg/amarok.kcfg
debian/tmp/usr/share/applications/kde/amarok.desktop
debian/tmp/usr/share/servicetypes/amarok_plugin.desktop
debian/tmp/usr/share/apps/konqueror/servicemenus/amarok_append.desktop

debian/tmp/usr/share/services/amarok_void-engine_plugin.desktop
debian/tmp/usr/lib/kde3/libamarok_void-engine_plugin.la
debian/tmp/usr/lib/kde3/libamarok_void-engine_plugin.so

debian/tmp/usr/bin/amarok
debian/tmp/usr/bin/amarokapp		/usr/lib/amarok
debian/tmp/usr/bin/amarok_xmmswrapper2	/usr/lib/amarok

debian/tmp/etc/*
