#ifndef _UADEMSG_H_
#define _UADEMSG_H_

#define UADE_REBOOT 1
#define UADE_SETSUBSONG 2
#define UADE_SONG_END 4
#define UADE_PLAYERNAME 6
#define UADE_MODULENAME 7
#define UADE_SUBSINFO 9
#define UADE_CHECKERROR 10
#define UADE_SCORECRASH 11
#define UADE_SCOREDEAD 12
#define UADE_GENERALMSG 13
#define UADE_NTSC 14
#define UADE_FORMATNAME 15
#define UADE_LOADFILE 16
#define UADE_READ 17
#define UADE_FILESIZE 18
#define UADE_TIME_CRITICAL 19
#define UADE_NO_INTERACTION 20
#define UADE_TOGGLE_LED 21

#endif
