METAS = {
 :specifiedtotalcount=>{:datatype=>:long, :code=>"mtco"},
 :dictionary=>{:datatype=>:container, :code=>"mdcl"},
 :itms_genreid=>{:datatype=>:long, :code=>"aeGI"},
 :norm_volume=>{:datatype=>:long, :code=>"aeNV"},
 :songtracknumber=>{:datatype=>:short, :code=>"astn"},
 :browsealbumlisting=>{:datatype=>:container, :code=>"abal"},
 :songcompilation=>{:datatype=>:char, :code=>"asco"},
 :smart_playlist=>{:datatype=>:char, :code=>"aeSP"},
 :songcomposer=>{:datatype=>:string, :code=>"ascp"},
 :songeqpreset=>{:datatype=>:string, :code=>"aseq"},
 :baseplaylist=>{:datatype=>:char, :code=>"abpl"},
 :supportsquery=>{:datatype=>:char, :code=>"msqy"},
 :itms_composerid=>{:datatype=>:long, :code=>"aeCI"},
 :contentcodesnumber=>{:datatype=>:long, :code=>"mcnm"},
 :databasebrowse=>{:datatype=>:container, :code=>"abro"},
 :songsize=>{:datatype=>:long, :code=>"assz"},
 :browsecomposerlisting=>{:datatype=>:container, :code=>"abcp"},
 :itms_artistid=>{:datatype=>:long, :code=>"aeAI"},
 :has_video=>{:datatype=>:char, :code=>"aeHV"},
 :statusstring=>{:datatype=>:string, :code=>"msts"},
 :authenticationschemes=>{:datatype=>:long, :code=>"msas"},
 :songcontentrating=>{:datatype=>:char, :code=>"ascr"},
 :itms_playlistid=>{:datatype=>:long, :code=>"aePI"},
 :status=>{:datatype=>:long, :code=>"mstt"},
 :supportsindex=>{:datatype=>:char, :code=>"msix"},
 :supportsresolve=>{:datatype=>:char, :code=>"msrs"},
 :contentcodesresponse=>{:datatype=>:container, :code=>"mccr"},
 :songdatakind=>{:datatype=>:char, :code=>"asdk"},
 :songartist=>{:datatype=>:string, :code=>"asar"},
 :songcodecsubtype=>{:datatype=>:long, :code=>"ascs"},
 :authenticationmethod=>{:datatype=>:char, :code=>"msau"},
 :season_num=>{:datatype=>:long, :code=>"aeSU"},
 :resolveinfo=>{:datatype=>:container, :code=>"arif"},
 :songcategory=>{:datatype=>:string, :code=>"asct"},
 :songformat=>{:datatype=>:string, :code=>"asfm"},
 :episode_num_str=>{:datatype=>:string, :code=>"aeEN"},
 :playlistshufflemode=>{:datatype=>:char, :code=>"apsm"},
 :browseartistlisting=>{:datatype=>:container, :code=>"abar"},
 :loginrequired=>{:datatype=>:char, :code=>"mslr"},
 :supportsextensions=>{:datatype=>:char, :code=>"msex"},
 :deletedidlisting=>{:datatype=>:container, :code=>"mudl"},
 :songdatemodified=>{:datatype=>:date, :code=>"asdm"},
 :songkeywords=>{:datatype=>:string, :code=>"asky"},
 :songdataurl=>{:datatype=>:string, :code=>"asul"},
 :music_sharing_version=>{:datatype=>:long, :code=>"aeSV"},
 :haschildcontainers=>{:datatype=>:char, :code=>"f\215ch"},
 :listing=>{:datatype=>:container, :code=>"mlcl"},
 :serverinforesponse=>{:datatype=>:container, :code=>"msrv"},
 :songdiscnumber=>{:datatype=>:short, :code=>"asdn"},
 :songtrackcount=>{:datatype=>:short, :code=>"astc"},
 :playlistsongs=>{:datatype=>:container, :code=>"apso"},
 :songcodectype=>{:datatype=>:long, :code=>"ascd"},
 :itemname=>{:datatype=>:string, :code=>"minm"},
 :itemcount=>{:datatype=>:long, :code=>"mimc"},
 :containercount=>{:datatype=>:long, :code=>"mctc"},
 :itms_storefrontid=>{:datatype=>:long, :code=>"aeSF"},
 :songrelativevolume=>{:datatype=>:char, :code=>"asrv"},
 :supportsupdate=>{:datatype=>:char, :code=>"msup"},
 :contentcodesname=>{:datatype=>:string, :code=>"mcna"},
 :songgrouping=>{:datatype=>:string, :code=>"agrp"},
 :itemkind=>{:datatype=>:char, :code=>"mikd"},
 :updateresponse=>{:datatype=>:container, :code=>"mupd"},
 :network_name=>{:datatype=>:string, :code=>"aeNN"},
 :songyear=>{:datatype=>:short, :code=>"asyr"},
 :episode_sort=>{:datatype=>:long, :code=>"aeES"},
 :itemid=>{:datatype=>:long, :code=>"miid"},
 :supportsbrowse=>{:datatype=>:char, :code=>"msbr"},
 :updatetype=>{:datatype=>:char, :code=>"muty"},
 :contentcodestype=>{:datatype=>:short, :code=>"mcty"},
 :databaseplaylists=>{:datatype=>:container, :code=>"aply"},
 :is_podcast_playlist=>{:datatype=>:char, :code=>"aePP"},
 :itms_songid=>{:datatype=>:long, :code=>"aeSI"},
 :songstoptime=>{:datatype=>:long, :code=>"assp"},
 :songlongcontentdescription=>{:datatype=>:string, :code=>"aslc"},
 :container=>{:datatype=>:container, :code=>"mcon"},
 :listingitem=>{:datatype=>:container, :code=>"mlit"},
 :songuserrating=>{:datatype=>:char, :code=>"asur"},
 :supportspersistentids=>{:datatype=>:char, :code=>"mspi"},
 :songsamplerate=>{:datatype=>:long, :code=>"assr"},
 :songdateadded=>{:datatype=>:date, :code=>"asda"},
 :songbitrate=>{:datatype=>:short, :code=>"asbr"},
 :containeritemid=>{:datatype=>:long, :code=>"mcti"},
 :parentcontainerid=>{:datatype=>:long, :code=>"mpco"},
 :databasescount=>{:datatype=>:long, :code=>"msdc"},
 :loginresponse=>{:datatype=>:container, :code=>"mlog"},
 :sessionid=>{:datatype=>:long, :code=>"mlid"},
 :serverrevision=>{:datatype=>:long, :code=>"musr"},
 :songdisabled=>{:datatype=>:char, :code=>"asdb"},
 :songdescription=>{:datatype=>:string, :code=>"asdt"},
 :bag=>{:datatype=>:container, :code=>"mbcl"},
 :supportsautologout=>{:datatype=>:char, :code=>"msal"},
 :timeoutinterval=>{:datatype=>:long, :code=>"mstm"},
 :songdisccount=>{:datatype=>:short, :code=>"asdc"},
 :songbeatsperminute=>{:datatype=>:short, :code=>"asbt"},
 :songgenre=>{:datatype=>:string, :code=>"asgn"},
 :playlistrepeatmode=>{:datatype=>:char, :code=>"aprm"},
 :songstarttime=>{:datatype=>:long, :code=>"asst"},
 :persistentid=>{:datatype=>:longlong, :code=>"mper"},
 :returnedcount=>{:datatype=>:long, :code=>"mrco"},
 :protocolversion=>{:datatype=>:version, :code=>"mpro"},
 :songcomment=>{:datatype=>:string, :code=>"ascm"},
 :is_podcast=>{:datatype=>:char, :code=>"aePC"},
 :series_name=>{:datatype=>:string, :code=>"aeSN"},
 :resolve=>{:datatype=>:container, :code=>"arsv"},
 :songalbum=>{:datatype=>:string, :code=>"asal"},
 :protocolversion=>{:datatype=>:version, :code=>"apro"},
 :serverdatabases=>{:datatype=>:container, :code=>"avdb"},
 :mediakind=>{:datatype=>:char, :code=>"aeMK"},
 :songtime=>{:datatype=>:long, :code=>"astm"},
 :databasesongs=>{:datatype=>:container, :code=>"adbs"},
 :browsegenrelisting=>{:datatype=>:container, :code=>"abgn"},
 :songcontentdescription=>{:datatype=>:string, :code=>"ascn"}
 }

CODE_TYPE = {
'aeNV'=>:long,
'astn'=>:short,
'aeGI'=>:long,
'mtco'=>:long,
'abal'=>:container,
'asco'=>:char,
'mdcl'=>:container,
'abpl'=>:char,
'aeSP'=>:char,
'ascp'=>:string,
'aseq'=>:string,
'msqy'=>:char,
'aeCI'=>:long,
'assz'=>:long,
'abcp'=>:container,
'mcnm'=>:long,
'aeAI'=>:long,
'abro'=>:container,
'aeHV'=>:char,
'msas'=>:long,
'ascr'=>:char,
'msts'=>:string,
'aePI'=>:long,
'mccr'=>:container,
'asdk'=>:char,
'msix'=>:char,
'msrs'=>:char,
'asar'=>:string,
'ascs'=>:long,
'mstt'=>:long,
'msau'=>:char,
'aeEN'=>:string,
'aeSU'=>:long,
'apsm'=>:char,
'asfm'=>:string,
'asct'=>:string,
'arif'=>:container,
'abar'=>:container,
'mudl'=>:container,
'asdm'=>:date,
'asky'=>:string,
'msex'=>:char,
'asul'=>:string,
'mslr'=>:char,
'aeSV'=>:long,
'astc'=>:short,
'f\215ch'=>:char,
'apso'=>:container,
'mlcl'=>:container,
'ascd'=>:long,
'asdn'=>:short,
'msrv'=>:container,
'mctc'=>:long,
'aeSF'=>:long,
'mimc'=>:long,
'minm'=>:string,
'asrv'=>:char,
'agrp'=>:string,
'mcna'=>:string,
'msup'=>:char,
'aeES'=>:long,
'mikd'=>:char,
'aeNN'=>:string,
'mupd'=>:container,
'asyr'=>:short,
'mcty'=>:short,
'aslc'=>:string,
'aply'=>:container,
'miid'=>:long,
'assp'=>:long,
'aeSI'=>:long,
'aePP'=>:char,
'muty'=>:char,
'msbr'=>:char,
'mlit'=>:mlit,
'mcon'=>:container,
'asur'=>:char,
'asda'=>:date,
'asbr'=>:short,
'assr'=>:long,
'mspi'=>:char,
'asdt'=>:string,
'mlog'=>:container,
'mlid'=>:long,
'asdb'=>:char,
'musr'=>:long,
'msdc'=>:long,
'mpco'=>:long,
'mcti'=>:long,
'asbt'=>:short,
'mbcl'=>:container,
'asgn'=>:string,
'asdc'=>:short,
'mstm'=>:long,
'msal'=>:char,
'aprm'=>:char,
'asst'=>:long,
'aeSN'=>:string,
'mrco'=>:long,
'arsv'=>:container,
'ascm'=>:string,
'aePC'=>:char,
'mper'=>:longlong,
'asal'=>:string,
'aeMK'=>:char,
'astm'=>:long,
'apro'=>:version,
'adbs'=>:container,
'avdb'=>:container,
'abgn'=>:container,
'ascn'=>:string}