METAS = { :songdateadded=>{:datatype=>Time, :code=>"asda"},
:itemname=>{:datatype=>Array, :code=>"minm" },
:browsegenrelisting=>{:datatype=>Array, :code=>"abgn"},
:playlistsongs=>{:datatype=>Array, :code=>"apso"},
:songcodecsubtype=>{:datatype=>Integer, :code=>"ascs"},
:songcontentdescription=>{:datatype=>String, :code=>"ascn"},
:songdescription=>{:datatype=>String, :code=>"asdt"},
:songdiscnumber=>{:datatype=>Integer, :code=>"asdn"},
:songuserrating=>{:datatype=>Integer, :code=>"asur"},
:songgrouping=>{:datatype=>String, :code=>"agrp"},
:songeqpreset=>{:datatype=>String, :code=>"aseq"},
:protocolversion=>{:datatype=>Integer, :code=>"apro"},
:songdatakind=>{:datatype=>Integer, :code=>"asdk"},
:songcompilation=>{:datatype=>Integer, :code=>"asco"},
:songalbum=>{:datatype=>String, :code=>"asal"},
:songdisabled=>{:datatype=>Integer, :code=>"asdb"},
:browseartistlisting=>{:datatype=>Array, :code=>"abar"},
:resolveinfo=>{:datatype=>Array, :code=>"arif"},
:songcategory=>{:datatype=>String, :code=>"asct"},
:songtracknumber=>{:datatype=>Integer, :code=>"astn"},
:databasesongs=>{:datatype=>Array, :code=>"adbs"},
:resolve=>{:datatype=>Array, :code=>"arsv"},
:songdisccount=>{:datatype=>Integer, :code=>"asdc"},
:playlistrepeatmode=>{:datatype=>Integer, :code=>"aprm"},
:songstarttime=>{:datatype=>Integer, :code=>"asst"},
:baseplaylist=>{:datatype=>Integer, :code=>"abpl"},
:songcodectype=>{:datatype=>Integer, :code=>"ascd"},
:songcomposer=>{:datatype=>String, :code=>"ascp"},
:songartist=>{:datatype=>String, :code=>"asar"},
:songstoptime=>{:datatype=>Integer, :code=>"assp"},
:songkeywords=>{:datatype=>String, :code=>"asky"},
:songformat=>{:datatype=>String, :code=>"asfm"},
:songtrackcount=>{:datatype=>Integer, :code=>"astc"},
:songsize=>{:datatype=>Integer, :code=>"assz"},
:browsecomposerlisting=>{:datatype=>Array, :code=>"abcp"},
:songcomment=>{:datatype=>String, :code=>"ascm"},
:songcontentrating=>{:datatype=>Integer, :code=>"ascr"},
:songsamplerate=>{:datatype=>Integer, :code=>"assr"},
:songbitrate=>{:datatype=>Integer, :code=>"asbr"},
:databaseplaylists=>{:datatype=>Array, :code=>"aply"},
:serverdatabases=>{:datatype=>Array, :code=>"avdb"},
:songdatemodified=>{:datatype=>Time, :code=>"asdm"},
:songlongcontentdescription=>{:datatype=>String, :code=>"aslc"},
:songtime=>{:datatype=>Integer, :code=>"astm"},
:songbeatsperminute=>{:datatype=>Integer, :code=>"asbt"},
:songgenre=>{:datatype=>String, :code=>"asgn"},
:databasebrowse=>{:datatype=>Array, :code=>"abro"},
:browsealbumlisting=>{:datatype=>Array, :code=>"abal"},
:playlistshufflemode=>{:datatype=>Integer, :code=>"apsm"},
:songyear=>{:datatype=>Integer, :code=>"asyr"},
:songrelativevolume=>{:datatype=>Integer, :code=>"asrv"},
:songdataurl=>{:datatype=>String, :code=>"asul"},
:itemid=>{:datatype=>Integer, :code=>"miid"}
}


