/* config-amarok.h. Generated by cmake from config-amarok.h.cmake */

/* Whether TagLib::FileName is a struct supporting wide characters or just a typedef */
#cmakedefine COMPLEX_TAGLIB_FILENAME 1

/* have module file format support in TagLib */
#cmakedefine TAGLIB_MOD_FOUND 1

/* have opus file format support in TagLib */
#cmakedefine TAGLIB_OPUS_FOUND 1

/* have QtOpenGL */
#cmakedefine QT_QTOPENGL_FOUND 1

/* If liblastfm is found */
#cmakedefine LIBLASTFM_FOUND 1
#ifdef LIBLASTFM_FOUND
#define HAVE_LIBLASTFM 1
#endif

/* If libofa is found */
#cmakedefine LIBOFA_FOUND 1
#ifdef LIBOFA_FOUND
#define HAVE_LIBOFA 1
#endif

/* Whether building with X11 dependent components */
#cmakedefine WITH_X11

/* Whether cmake build type is debug */
#cmakedefine DEBUG_BUILD_TYPE
