######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 3 14:53:32 2008
######################################################################

QT += testlib xml network sql
CONFIG += core types fingerprint

include( $$ROOT_DIR/common/qmake/include.pro )

TEMPLATE = app
TARGET = 
DEPENDPATH += . 
INCLUDEPATH += .

# Input
SOURCES += TestFingerprintGenerator.cpp
