# - Try to find the GTACFEAT library
# Once done this will define
#
#  GTACFEAT_FOUND - system has the GTACFEAT library
#  GTACFEAT_INCLUDE_DIR - the GTACFEAT include directory
#  GTACFEAT_LIBRARIES - The libraries needed to use GTACFEAT

if (GTACFEAT_INCLUDE_DIR AND GTACFEAT_LIBRARIES)
  # Already in cache, be silent
  set(Mp4v2_FIND_QUIETLY TRUE)
endif (GTACFEAT_INCLUDE_DIR AND GTACFEAT_LIBRARIES)

FIND_PATH(GTACFEAT_INCLUDE_DIR gtacfeat/fingerprint.h)

FIND_LIBRARY(GTACFEAT_LIBRARY NAMES gtacfeat)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GTACFEAT DEFAULT_MSG GTACFEAT_LIBRARY GTACFEAT_INCLUDE_DIR)

MARK_AS_ADVANCED(GTACFEAT_INCLUDE_DIR GTACFEAT_LIBRARY)
