# - Try to find the Taglib library
# Once done this will define
#
#  TAGLIB_FOUND - system has the taglib library
#  TAGLIB_INCLUDE_DIR - the taglib include dir
#  TAGLIB_LIBRARIES - The libraries needed to use taglib
#
# Copyright (c) 2006, Laurent Montel, <montel@kde.org>
# Copyright (c) 2007, Dan Meltzer, <hydrogen@notyetimplemented.com>
#
# Redistribution and use is allowed according to the terms of the BSD license.
# For details see the accompanying COPYING-CMAKE-SCRIPTS file.


IF (TAGLIB_INCLUDE_DIR AND TAGLIB_LIBRARIES AND TAGLIB_INTERFACE_LIBRARY)
   # in cache already
   SET(TAGLIB_FIND_QUIETLY TRUE)
ELSE (TAGLIB_INCLUDE_DIR AND TAGLIB_LIBRARIES AND TAGLIB_INTERFACE_LIBRARY)
   SET(TAGLIB_FIND_QUIETLY FALSE)
ENDIF (TAGLIB_INCLUDE_DIR AND TAGLIB_LIBRARIES AND TAGLIB_INTERFACE_LIBRARY)


INCLUDE(UsePkgConfig)
PKGCONFIG(taglib _taglibIncDir _taglibLinkDir _taglibLinkFlags _taglibCflags)


FIND_PATH(TAGLIB_INCLUDE_DIR tag.h
   PATHS
   ${_taglibIncDir}
   )

FIND_LIBRARY(TAGLIB_LIBRARIES NAMES tag
   PATHS
   ${_taglibLinkDir}
   )

IF (TAGLIB_INCLUDE_DIR)
ELSE (TAGLIB_INCLUDE_DIR)
   MESSAGE(STATUS "Taglib: WARNING: include dir not found")
ENDIF (TAGLIB_INCLUDE_DIR)

IF (TAGLIB_LIBRARIES)
ELSE (TAGLIB_LIBRARIES)
   MESSAGE(STATUS "Taglib: WARNING: library not found")
ENDIF (TAGLIB_LIBRARIES)

IF (TAGLIB_INCLUDE_DIR AND TAGLIB_LIBRARIES)
   SET(TAGLIB_FOUND TRUE)
ELSE (TAGLIB_INCLUDE_DIR AND TAGLIB_LIBRARIES)
   SET(TAGLIB_FOUND FALSE)
ENDIF (TAGLIB_INCLUDE_DIR AND TAGLIB_LIBRARIES)

IF (TAGLIB_FOUND)
   IF (NOT TAGLIB_FIND_QUIETLY)
      MESSAGE(STATUS "Found Taglib: ${TAGLIB_LIBRARIES}")
   ENDIF (NOT TAGLIB_FIND_QUIETLY)
ELSE (TAGLIB_FOUND)
   IF (TAGLIB_FIND_REQUIRED)
      MESSAGE(SEND_ERROR "Could NOT find Taglib")
   ENDIF (TAGLIB_FIND_REQUIRED)
ENDIF (TAGLIB_FOUND)

MARK_AS_ADVANCED(GSTREAMER_INCLUDE_DIR GSTREAMER_LIBRARIES)
